//version 1.1.0
const { Command } = require('commander');
const yaml = require('yaml');
const fs = require('fs/promises');
const axios = require('axios');

const program = new Command();

program
  .name('probe-cli') 
  .description(`A lightweight command-line interface (CLI) tool designed for efficient API health checks and automated endpoint testing.
  
  To get started, generate a sample configuration file using 'probe init'.
  Then, define your API endpoints in a YAML file (e.g., config.yml), and probe-cli will execute requests,
  validate responses, and report on their status.
  
  Built by revelo. Find out more at www.revelo.software/probe-cli`) 
  .version('1.1.0');

program.addHelpText('afterAll', `
Examples:
  $ probe run                                 # Runs all tests using the default config.yml
  $ probe run -c my-custom-config.yml       # Runs all tests using a specified config file
  $ probe run --api "GitHub API Status"     # Runs only the "GitHub API Status" test
  $ probe init                                # Creates a sample config.yml file in the current directory
`);

program
  .command('init')
  .description('Creates a sample config.yml file in the current directory.')
  .action(async () => {
    const defaultConfigContent = `
# config.yml - Configuration file for API monitoring and testing
# This is an example configuration generated by probe-cli init.
# You can modify this file to add, remove, or change API probes.
apis:
  - name: GitHub API Status
    url: https://www.githubstatus.com/api/v2/status.json
    method: GET
    expectedStatus: 200
    timeout: 5000

# You can add more APIs here:
#  - name: My Other API
#    url: https://api.example.com/health
#    method: GET
#    expectedStatus: 200
#    timeout: 5000

#Need more help? Visit www.revelo.software/probe-cli 
    `;

    const filePath = 'config.yml';
    try {
      await fs.writeFile(filePath, defaultConfigContent.trim());
      console.log(`Successfully created sample config file: ${filePath}`);
      console.log('You can now edit this file and run `probe run`');
    } catch (error) {
      console.error(`Error creating config file: ${error.message}`);
      process.exit(1);
    }
  });


program
  .command('run')
  .description('Starts the API monitoring and testing process.')
  .option('-c, --config <file>', 'Path to the configuration file', 'config.yml')
  .option('-a, --api <name>', 'Run only a specific API test by its name (as defined in config.yml)')
  .action(async (options) => {
    console.log('Starting API health check and test runner...');
    console.log(`Using config file: ${options.config}`);

    try {
      const configFileContent = await fs.readFile(options.config, 'utf8');
      const config = yaml.parse(configFileContent);

      if (!config.apis || !Array.isArray(config.apis) || config.apis.length === 0) {
        console.warn("No 'apis' section found, or it's empty/not an array in the config file. Exiting.");
        process.exit(0); 
      }

      let apisToMonitor = config.apis;

      if (options.api) {
        apisToMonitor = config.apis.filter(api => api.name === options.api);
        if (apisToMonitor.length === 0) {
          console.error(`Error: No API found with the name "${options.api}" in the config file.`);
          process.exit(1);
        }
        console.log(`Found 1 specific API to monitor: "${options.api}". Initiating check...`);
      } else {
        console.log(`Found ${apisToMonitor.length} APIs to monitor. Initiating checks...`);
      }

      for (const api of apisToMonitor) {
        console.log(`\n--- Checking API: ${api.name} ---`);
        const startTime = process.hrtime.bigint();

        try {
          const response = await axios({
            method: api.method || 'GET', 
            url: api.url,
            timeout: api.timeout || 10000, 
            validateStatus: null 
          });

          const endTime = process.hrtime.bigint(); 
          const responseTimeMs = Number(endTime - startTime) / 1_000_000; 

          const statusCheck = response.status === api.expectedStatus;

          const dataSize = response.data ? JSON.stringify(response.data).length : 0;
          
          console.log(`  URL: ${api.url}`);
          console.log(`  Method: ${api.method || 'GET'}`);
          console.log(`  Response Time: ${responseTimeMs.toFixed(2)} ms`); 
          console.log(`  Actual Status: ${response.status}`);
          console.log(`  Expected Status: ${api.expectedStatus}`);
          console.log(`  Status Match: ${statusCheck ? 'PASS' : 'FAIL'}`);
          console.log(`  Response Data Size: ${dataSize} bytes`);

          if (response.data) {
            const responseDataString = JSON.stringify(response.data);
            const responseDataSnippet = responseDataString.substring(0, 200) + (responseDataString.length > 200 ? '...' : '');
            console.log(`  Response Body Snippet: ${responseDataSnippet}`);
          }


          if (!statusCheck) {
            console.error(`  ERROR: Status mismatch for ${api.name}`);
          }

          
        } catch (error) {
          const endTime = process.hrtime.bigint(); 
          const responseTimeMs = Number(endTime - startTime) / 1_000_000;

          console.error(`  ERROR checking ${api.name} (${api.url}):`);
          console.error(`  Response Time: ${responseTimeMs.toFixed(2)} ms`); 
          if (error.response) {

            console.error(`  Status: ${error.response.status || 'N/A'}`);
            console.error(`  Response Data: ${JSON.stringify(error.response.data || 'No data')}`);
          } else if (axios.isCancel(error)) {

            console.error(`  Issue: Request timed out.`);
          } else if (error.request) {

            console.error(`  Issue: No response received. Possible network issue or target down.`);
            console.error(`  Message: ${error.message}`);
          } else {

            console.error(`  Issue: Could not send request or unexpected error.`);
            console.error(`  Message: ${error.message}`);
          }
        }
      }

      console.log('\n--- API checks complete. ---');

    } catch (error) {
      console.error(`Error loading or processing configuration: ${error.message}`);
      process.exit(1);
    }
  });

program.parse(process.argv); 