#!/usr/bin/env node

const { Command } = require('commander');
const yaml = require('yaml');
const fs = require('fs/promises');
const axios = require('axios');

const program = new Command();

// --- START: Program Description and Help Improvements ---
program
  .name('probe-cli') // This name is used internally by Commander for "Usage" line
  .description(`A lightweight command-line interface (CLI) tool designed for efficient API health checks and automated endpoint testing.
  
  To get started, generate a sample configuration file using 'probe init'.
  Then, define your API endpoints in a YAML file (e.g., config.yml), and probe-cli will execute requests,
  validate responses, and report on their status.
  
  Built by revelo. Find out more at www.revelo.software/probe-cli`) // CORRECTED: Clarified config file creation
  .version('1.0.0');

// Add examples to the help text - CORRECTED TO USE 'probe'
program.addHelpText('afterAll', `
Examples:
  $ probe run                                 # Runs all tests using the default config.yml
  $ probe run -c my-custom-config.yml       # Runs all tests using a specified config file
  $ probe run --api "GitHub API Status"     # Runs only the "GitHub API Status" test
  $ probe init                                # Creates a sample config.yml file in the current directory
`);
// --- END: Program Description and Help Improvements ---


// --- START: New 'init' command ---
program
  .command('init')
  .description('Creates a sample config.yml file in the current directory.')
  .action(async () => {
    const defaultConfigContent = `
# config.yml - Configuration file for API monitoring and testing
# This is an example configuration generated by probe-cli init.
# You can modify this file to add, remove, or change API probes.
apis:
  - name: GitHub API Status
    url: https://www.githubstatus.com/api/v2/status.json
    method: GET
    expectedStatus: 200
    timeout: 5000

# You can add more APIs here:
#  - name: My Other API
#    url: https://api.example.com/health
#    method: GET
#    expectedStatus: 200
#    timeout: 5000

#Need more help? Visit www.revelo.software/probe-cli 
    `;

    const filePath = 'config.yml';
    try {
      await fs.writeFile(filePath, defaultConfigContent.trim());
      console.log(`Successfully created sample config file: ${filePath}`);
      console.log('You can now edit this file and run `probe run`');
    } catch (error) {
      console.error(`Error creating config file: ${error.message}`);
      process.exit(1);
    }
  });
// --- END: New 'init' command ---


program
  .command('run')
  .description('Starts the API monitoring and testing process.')
  .option('-c, --config <file>', 'Path to the configuration file', 'config.yml')
  .option('-a, --api <name>', 'Run only a specific API test by its name (as defined in config.yml)') // NEW: Option for specific API
  .action(async (options) => {
    console.log('Starting API health check and test runner...');
    console.log(`Using config file: ${options.config}`);

    try {
      const configFileContent = await fs.readFile(options.config, 'utf8');
      const config = yaml.parse(configFileContent);

      if (!config.apis || !Array.isArray(config.apis) || config.apis.length === 0) {
        console.warn("No 'apis' section found, or it's empty/not an array in the config file. Exiting.");
        process.exit(0); // Exit gracefully if no APIs to monitor
      }

      let apisToMonitor = config.apis;

      // --- NEW LOGIC: Filter APIs if --api option is provided ---
      if (options.api) {
        apisToMonitor = config.apis.filter(api => api.name === options.api);
        if (apisToMonitor.length === 0) {
          console.error(`Error: No API found with the name "${options.api}" in the config file.`);
          process.exit(1);
        }
        console.log(`Found 1 specific API to monitor: "${options.api}". Initiating check...`);
      } else {
        console.log(`Found ${apisToMonitor.length} APIs to monitor. Initiating checks...`);
      }
      // --- END NEW LOGIC ---

      // Iterate through each API (either all or the filtered specific one)
      for (const api of apisToMonitor) {
        console.log(`\n--- Checking API: ${api.name} ---`);
        const startTime = process.hrtime.bigint(); // Start timer for response time

        try {
          const response = await axios({
            method: api.method || 'GET', // Default to GET if not specified
            url: api.url,
            timeout: api.timeout || 10000, // Default to 10 seconds if not specified
            validateStatus: null // Do not throw error for non-2xx status codes; allows custom status check
          });

          const endTime = process.hrtime.bigint(); // End timer
          const responseTimeMs = Number(endTime - startTime) / 1_000_000; // Convert to milliseconds

          // Check if the actual status matches the expected status
          const statusCheck = response.status === api.expectedStatus;

          // Determine response data size
          const dataSize = response.data ? JSON.stringify(response.data).length : 0;
          
          console.log(`  URL: ${api.url}`);
          console.log(`  Method: ${api.method || 'GET'}`);
          console.log(`  Response Time: ${responseTimeMs.toFixed(2)} ms`); // Log response time
          console.log(`  Actual Status: ${response.status}`);
          console.log(`  Expected Status: ${api.expectedStatus}`);
          console.log(`  Status Match: ${statusCheck ? 'PASS' : 'FAIL'}`);
          console.log(`  Response Data Size: ${dataSize} bytes`);
          // Log a snippet of the response data, especially for failures or when content checks might be added
          if (response.data) {
            const responseDataString = JSON.stringify(response.data);
            const responseDataSnippet = responseDataString.substring(0, 200) + (responseDataString.length > 200 ? '...' : '');
            console.log(`  Response Body Snippet: ${responseDataSnippet}`);
          }


          if (!statusCheck) {
            console.error(`  ERROR: Status mismatch for ${api.name}`);
          }
          // You can add more detailed checks here (e.g., response body content, specific headers)

        } catch (error) {
          const endTime = process.hrtime.bigint(); // End timer even on error
          const responseTimeMs = Number(endTime - startTime) / 1_000_000;

          console.error(`  ERROR checking ${api.name} (${api.url}):`);
          console.error(`  Response Time: ${responseTimeMs.toFixed(2)} ms`); // Log response time even on error
          if (error.response) {
            // The request was made and the server responded with a status code
            // that falls out of the range of 2xx
            console.error(`  Status: ${error.response.status || 'N/A'}`);
            console.error(`  Response Data: ${JSON.stringify(error.response.data || 'No data')}`);
          } else if (axios.isCancel(error)) {
            // Request was cancelled (e.g., due to timeout)
            console.error(`  Issue: Request timed out.`);
          } else if (error.request) {
            // The request was made but no response was received (e.g., network error)
            console.error(`  Issue: No response received. Possible network issue or target down.`);
            console.error(`  Message: ${error.message}`); // Original error message
          } else {
            // Something else happened while setting up the request that triggered an Error
            console.error(`  Issue: Could not send request or unexpected error.`);
            console.error(`  Message: ${error.message}`);
          }
        }
      }

      console.log('\n--- API checks complete. ---');

    } catch (error) {
      console.error(`Error loading or processing configuration: ${error.message}`);
      process.exit(1); // Exit with an error code for config issues
    }
  });

program.parse(process.argv); // This line must be at the very end to parse commands